/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MdSideDrawer {
        "drawerTitle": string;
        "open": boolean;
        "openDrawer": () => Promise<void>;
    }
}
declare global {
    interface HTMLMdSideDrawerElement extends Components.MdSideDrawer, HTMLStencilElement {
    }
    var HTMLMdSideDrawerElement: {
        prototype: HTMLMdSideDrawerElement;
        new (): HTMLMdSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "md-side-drawer": HTMLMdSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface MdSideDrawer {
        "drawerTitle"?: string;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "md-side-drawer": MdSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "md-side-drawer": LocalJSX.MdSideDrawer & JSXBase.HTMLAttributes<HTMLMdSideDrawerElement>;
        }
    }
}
